---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "bookmydrapp"
  namespace: "default"
  labels:
    app: "bookmydrapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "bookmydrapp"
  template:
    metadata:
      labels:
        app: "bookmydrapp"
    spec:
      containers:
      - name: "bookmydrapp-sha256-1"
        image: "gcr.io/charged-ground-326209/github.com/rukminiak041/bookmydrapp@sha256:07ebf8915306f3eaf648149c5dd0b7b3e7a86dee55ac1a2580a80d321716b32e"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "bookmydrapp-hpa-dpjl"
  namespace: "default"
  labels:
    app: "bookmydrapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "bookmydrapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
